# This workflow  do a clean sinstallation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  IMAGE_TAG: ${{ github.run_number }}


jobs:
  compile:

    runs-on: Agent-1

    steps:
     - name: checkout repo
       uses: actions/checkout@v4
     - name: Use Node.js
       uses: actions/setup-node@v4
       with:
        node-version: '23'

     - name: frontend syntax checks
       run: |
         cd client
         find . -name "*.js" -exec node --check {} +


     - name: backend syntax check
       run: |
          cd api    
          find . -name "*.js" -exec node --check {} +
          
  gitleaks_scan:
   runs-on: Agent-1
   needs: compile

   steps:
     - name: Checkout repo
       uses: actions/checkout@v4

     - name: Install Gitleaks v8
       run: |
        curl -sSL https://github.com/gitleaks/gitleaks/releases/download/v8.24.3/gitleaks_8.24.3_linux_x64.tar.gz | tar -xz
        sudo mv gitleaks /usr/local/bin/gitleaks

     - name: Run Gitleaks (client)
       run: gitleaks detect --source ./client --exit-code 1

     - name: Run Gitleaks (api)
       run: gitleaks detect --source ./api --exit-code 1
       
  trivy-scan:
     runs-on: Agent-1
     needs: gitleaks_scan

     steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: trivy run
        uses: aquasecurity/trivy-action@0.24.0
        with:
          scan-type: fs
          scan-ref: '.'
          format: table
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          
  sonar-frontends:
   runs-on: Agent-1
   needs: trivy-scan


   steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: SonarQube Scan (Frontend)
      uses: SonarSource/sonarqube-scan-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{vars.SONAR_HOST_URL }}
      with:
        projectBaseDir: client
        args: >
          -Dsonar.projectKey=myorg_frontend
          -Dsonar.projectName=myorg_frontend
          -Dsonar.exclusions=**/node_modules/**,**/dist/**,**/build/**

          

  sonar-backend:
   runs-on: Agent-1
   needs: sonar-frontends

   steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: SonarQube Scan (Backend)
      uses: sonarsource/sonarqube-scan-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}
      with:
        projectBaseDir: api
        args: >
          -Dsonar.projectKey=myorg_api
          -Dsonar.projectName=myorg_api
          -Dsonar.sources=.
          -Dsonar.exclusions=**/node_modules/**,**/dist/**,**/build/**
  build-frontend-and-push-nexus:
   runs-on: Agent-1
   needs: sonar-backend

   steps:
   - name: Checkout code
     uses: actions/checkout@v4

   - name: Login to Nexus
     run: |
      echo "${{ secrets.NEXUS_PASSWORD }}" | docker login \
        ${{ secrets.NEXUS_REGISTRY }} \
        -u "${{ secrets.NEXUS_USERNAME }}" \
        --password-stdin

   - name: Build frontend image
     run: |
      docker build -t frontend:${IMAGE_TAG} ./client

   - name: Trivy scan frontend image
     uses: aquasecurity/trivy-action@0.24.0
     with:
      image-ref: frontend:${IMAGE_TAG}
      severity: HIGH,CRITICAL
      vuln-type: os,library
      ignore-unfixed: true
      exit-code: '1'

   - name: Tag & Push frontend image
     run: |
      docker tag frontend:${IMAGE_TAG} \
        ${{ secrets.NEXUS_REGISTRY }}/${{ secrets.NEXUS_REPO }}/frontend:${IMAGE_TAG}

      docker push \
        ${{ secrets.NEXUS_REGISTRY }}/${{ secrets.NEXUS_REPO }}/frontend:${IMAGE_TAG}

        
  build-backend-and-push-nexus:
   runs-on: Agent-1
   needs: build-frontend-and-push-nexus

   steps:
   - name: Checkout code
     uses: actions/checkout@v4

   - name: Login to Nexus
     run: |
      echo "${{ secrets.NEXUS_PASSWORD }}" | docker login \
        ${{ secrets.NEXUS_REGISTRY }} \
        -u "${{ secrets.NEXUS_USERNAME }}" \
        --password-stdin

   - name: Build backend image
     run: |
      docker build -t backend:${IMAGE_TAG} ./api

   - name: Trivy scan backend image
     uses: aquasecurity/trivy-action@0.24.0
     with:
      image-ref: backend:${IMAGE_TAG}
      severity: HIGH,CRITICAL
      vuln-type: os,library
      ignore-unfixed: true
      exit-code: '1'

   - name: Tag & Push backend image
     run: |
      docker tag backend:${IMAGE_TAG} \
        ${{ secrets.NEXUS_REGISTRY }}/${{ secrets.NEXUS_REPO }}/backend:${IMAGE_TAG}

      docker push \
        ${{ secrets.NEXUS_REGISTRY }}/${{ secrets.NEXUS_REPO }}/backend:${IMAGE_TAG}



