# This workflow  do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  compile:

    runs-on: Agent-1

    steps:
     - name: checkout repo
       uses: actions/checkout@v4
     - name: Use Node.js
       uses: actions/setup-node@v4
       with:
        node-version: '23'

     - name: frontend syntax checks
       run: |
         cd client
         find . -name "*.js" -exec node --check {} +


     - name: backend syntax check
       run: |
          cd api    
          find . -name "*.js" -exec node --check {} +
          
  gitleaks_scan:
   runs-on: Agent-1
   needs: compile

   steps:
     - name: Checkout repo
       uses: actions/checkout@v4

     - name: Install Gitleaks v8
       run: |
        curl -sSL https://github.com/gitleaks/gitleaks/releases/download/v8.24.3/gitleaks_8.24.3_linux_x64.tar.gz | tar -xz
        sudo mv gitleaks /usr/local/bin/gitleaks

     - name: Run Gitleaks (client)
       run: gitleaks detect --source ./client --exit-code 1

     - name: Run Gitleaks (api)
       run: gitleaks detect --source ./api --exit-code 1
       
  trivy-scan:
     runs-on: Agent-1
     needs: gitleaks_scan

     steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: trivy run
        uses: aquasecurity/trivy-action@0.24.0
        with:
          scan-type: fs
          scan-ref: '.'
          format: table
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
  sonar-frontends:
   runs-on: Agent-1
   needs: trivy-scan

   steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: SonarQube Scan (Frontend)
      uses: sonarsource/sonarqube-scan-action@master
      with:
        projectBaseDir: client
        args: >
          -Dsonar.projectKey=myorg_client
          -Dsonar.projectName=myorg_client
          -Dsonar.sources=.
          -Dsonar.exclusions=**/node_modules/**,**/dist/**,**/build/**
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

  sonar-backend:
       runs-on: Agent-1
       needs: sonar-frontends
       
       steps:
         - name: checkout repo
           uses: actions/checkout@v4
         - name: sonar update  
           uses: sonarsource/sonarqube-scan-action@master
           with:
              projectBaseDir: api
              args: >
               -Dsonar.projectKey=myorg_api
               -Dsonar.projectName=myorg_api
               -Dsonar.sources=.
               -Dsonar.exclusions=**/node_modules/**,**/dist/**,**/build/**
           env: 
             SONAR_TOKEN: ${{secrets.SONAR_TOKEN }}
             SONAR_HOST_URL: ${{secrets.SONAR_HOST_URL}}     
             
  build-frontend-and-push-docker-image:
    runs-on: Agent-1
    needs: sonar-backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
         username: ${{vars.DOCKERHUB_USERNAME}}
         password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push frontend image
        uses: docker/build-push-action@v6
        with:
         context: ./client
         file: ./client/Dockerfile
         push: true
         tags: javithmj/frontend:latest


  build-backend-and-push-docker-image:
    runs-on: Agent-1
    needs: build-frontend-and-push-docker-image

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
         username: ${{ vars.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push backend image
        uses: docker/build-push-action@v6
        with:
          context: ./api
          file: ./api/Dockerfile
          push: true
          tags: javithmj/backend:latest

               
