# This workflow  do a clean sinstallation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  compile:

    runs-on: Agent-1

    steps:
     - name: checkout repo
       uses: actions/checkout@v4
     - name: Use Node.js
       uses: actions/setup-node@v4
       with:
        node-version: '23'

     - name: frontend syntax checks
       run: |
         cd client
         find . -name "*.js" -exec node --check {} +


     - name: backend syntax check
       run: |
          cd api    
          find . -name "*.js" -exec node --check {} +
          
  gitleaks_scan:
   runs-on: Agent-1
   needs: compile

   steps:
     - name: Checkout repo
       uses: actions/checkout@v4

     - name: Install Gitleaks v8
       run: |
        curl -sSL https://github.com/gitleaks/gitleaks/releases/download/v8.24.3/gitleaks_8.24.3_linux_x64.tar.gz | tar -xz
        sudo mv gitleaks /usr/local/bin/gitleaks

     - name: Run Gitleaks (client)
       run: gitleaks detect --source ./client --exit-code 1

     - name: Run Gitleaks (api)
       run: gitleaks detect --source ./api --exit-code 1
       
  trivy-scan:
     runs-on: Agent-1
     needs: gitleaks_scan

     steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: trivy run
        uses: aquasecurity/trivy-action@0.24.0
        with:
          scan-type: fs
          scan-ref: '.'
          format: table
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          
  sonar-frontends:
   runs-on: Agent-1
   needs: trivy-scan


   steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: SonarQube Scan (Frontend)
      uses: SonarSource/sonarqube-scan-action@v2
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{vars.SONAR_HOST_URL }}
      with:
        projectBaseDir: client
        args: >
          -Dsonar.projectKey=myorg_frontend
          -Dsonar.projectName=myorg_frontend
          -Dsonar.exclusions=**/node_modules/**,**/dist/**,**/build/**

          

  sonar-backend:
       runs-on: Agent-1
       needs: sonar-frontends
       
       steps:
         - name: checkout repo
           uses: actions/checkout@v4
            
         - name: sonar update  
           uses: sonarsource/sonarqube-scan-action@v2
           with:
              projectBaseDir: api
              args: >
               -Dsonar.projectKey=myorg_api
               -Dsonar.projectName=myorg_api
               -Dsonar.sources=.
               -Dsonar.exclusions=**/node_modules/**,**/dist/**,**/build/**
           env: 
             SONAR_TOKEN: ${{secrets.SONAR_TOKEN }}
             SONAR_HOST_URL: ${{secrets.SONAR_HOST_URL}}     
             
  build-frontend-and-push-nexus:
    runs-on: Agent-1
    needs: sonar-backend

    steps:
    - uses: actions/checkout@v4

    - name: Login to Nexus
      run: |
        echo "${{ secrets.NEXUS_PASSWORD }}" | docker login ${{ secrets.NEXUS_REGISTRY }} \
          -u "${{ secrets.NEXUS_USERNAME }}" --password-stdin

    - name: Build frontend image (local)
      run: |
        docker build -t frontend:scan ./client

    - name: Trivy scan frontend image
      uses: aquasecurity/trivy-action@0.24.0
      with:
        image-ref: frontend:scan
        severity: CRITICAL,HIGH
        ignore-unfixed: true
        exit-code: '1'

    - name: Push frontend image to Nexus
      run: |
        docker tag frontend:scan ${{ secrets.NEXUS_REGISTRY }}/${{ secrets.NEXUS_REPO }}/frontend:latest
        docker push ${{ secrets.NEXUS_REGISTRY }}/${{ secrets.NEXUS_REPO }}/frontend:latest

        
  build-backend-and-push-nexus:
    runs-on: Agent-1
    needs: build-frontend-and-push-nexus

    steps:
    - uses: actions/checkout@v4

    - name: Login to Nexus
      run: |
        echo "${{ secrets.NEXUS_PASSWORD }}" | docker login ${{ secrets.NEXUS_REGISTRY }} \
          -u "${{ secrets.NEXUS_USERNAME }}" --password-stdin

    - name: Build backend image (local)
      run: |
        docker build -t backend:scan ./api

    - name: Trivy scan backend image
      uses: aquasecurity/trivy-action@0.24.0
      with:
        image-ref: backend:scan
        severity: CRITICAL,HIGH
        ignore-unfixed: true
        exit-code: '1'

    - name: Push backend image to Nexus
      run: |
        docker tag backend:scan ${{ secrets.NEXUS_REGISTRY }}/${{ secrets.NEXUS_REPO }}/backend:latest
        docker push ${{ secrets.NEXUS_REGISTRY }}/${{ secrets.NEXUS_REPO }}/backend:latest


